version: '2'
services:
    jhipster_backend-app:
        image: jhipster_backend
        environment:
            - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://jhipster_backend-mysql:3306/jhipster_backend?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    jhipster_backend-mysql:
        extends:
            file: mysql.yml
            service: jhipster_backend-mysql
